import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next";
import { AuthClientProvider } from "better-auth/react";
import { authClient } from "@/lib/auth-client";

const inter = Inter({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
    <TRPCReactProvider>
      <html lang="en">
        <body 
        className={`${inter.className} antialiased`}>
          <AuthClientProvider client={authClient}>
            <Toaster/>
            {children}
          </AuthClientProvider>
          </body>
      </html>
    </TRPCReactProvider>
    </NuqsAdapter>
  );
}
